development:
  adapter: postgresql
  encoding: unicode
  database: blocmetrics_development
  pool: 5
  username: caroline
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: blocmetrics_test
  pool: 5
  username: caroline
  password:
  timeout: 5000
